# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Path to the directory containing manifests
resources:
- manifests/deployment.yaml
- manifests/service.yaml

# Common labels to be added to all resources
commonLabels:
  app: nginx-example
  environment: dev

